-- 002_lista_espera.sql
-- Tabela para gerenciamento da Lista de Espera por horário ou médico.

CREATE TABLE IF NOT EXISTS public.lista_espera (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id BIGINT REFERENCES public.usuarios(id) ON DELETE CASCADE,
  medico_id BIGINT REFERENCES public.usuarios(id) ON DELETE CASCADE,
  data_alvo DATE NOT NULL,
  horario_alvo TIME, -- Opcional: pode querer qualquer horário no dia
  status VARCHAR(20) DEFAULT 'AGUARDANDO' CHECK (status IN ('AGUARDANDO', 'NOTIFICADO', 'CONCLUIDO', 'EXPIRADO', 'CANCELADO')),
  notificado_em TIMESTAMP WITH TIME ZONE,
  criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Como o backend (app.js) utiliza a service_role_key e JWT próprio, RLS com auth.uid()
-- falharia (tipos incompatíveis e auth.uid não existe no contexto do service_role_key).
ALTER TABLE public.lista_espera ENABLE ROW LEVEL SECURITY;

CREATE POLICY "lista_espera_allow_all_service" ON public.lista_espera FOR ALL USING (true);
