require('dotenv').config({ path: '.env' });
const supabase = require('./config/db.js');
async function test() {
  await supabase.rpc('execute_sql', { sql: 'DROP TABLE IF EXISTS public.lista_espera CASCADE;' });
  
  const createSql = `
CREATE TABLE public.lista_espera (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id BIGINT REFERENCES public.usuarios(id) ON DELETE CASCADE,
  medico_id BIGINT REFERENCES public.usuarios(id) ON DELETE CASCADE,
  data_alvo DATE NOT NULL,
  horario_alvo TIME,
  status VARCHAR(20) DEFAULT 'AGUARDANDO' CHECK (status IN ('AGUARDANDO', 'NOTIFICADO', 'CONCLUIDO', 'EXPIRADO', 'CANCELADO')),
  notificado_em TIMESTAMP WITH TIME ZONE,
  criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.lista_espera ENABLE ROW LEVEL SECURITY;
CREATE POLICY "lista_espera_allow_all_service" ON public.lista_espera FOR ALL USING (true);
NOTIFY pgrst, 'reload schema';
`;
  const { error } = await supabase.rpc('execute_sql', { sql: createSql });
  console.log('Error creating table:', error);
}
test();
